# Generated by Django 5.1.3 on 2024-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='moderatorprofile',
            name='lang',
            field=models.CharField(choices=[('cro', 'Croatian'), ('eng', 'English'), ('ger', 'German')], default='eng', max_length=3),
        ),
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.CharField(choices=[('cro', 'Croatian'), ('eng', 'English'), ('ger', 'German')], default='eng', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('YN', 'Yes/No'), ('MC', 'Multiple Choice')], max_length=2),
        ),
        migrations.DeleteModel(
            name='BlankInputQuestion',
        ),
    ]
