# Generated by Django 5.1.3 on 2024-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_total_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yesnoquestion',
            name='correct_option',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=5),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=1),
        ),
    ]
