# Generated by Django 5.1.3 on 2024-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_yesnoquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='selected_option',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
